# Generated by Django 3.2.12 on 2024-03-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='articles',
            field=models.ManyToManyField(to='public.ArticleUploadedEvent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photos',
            field=models.ManyToManyField(to='public.PhotoUploadedEvent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='videos',
            field=models.ManyToManyField(to='public.VideoUploadedEvent'),
        ),
    ]
