# Generated by Django 3.2.12 on 2024-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240312_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleUploadedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoUploadedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoUploadedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='articles',
            field=models.ManyToManyField(blank=True, to='accounts.ArticleUploadedEvent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photos',
            field=models.ManyToManyField(blank=True, to='accounts.PhotoUploadedEvent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='videos',
            field=models.ManyToManyField(blank=True, to='accounts.VideoUploadedEvent'),
        ),
    ]
