# Generated by Django 3.2.12 on 2024-03-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240312_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='videos',
        ),
    ]
