# Generated by Django 3.2.12 on 2024-03-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleUploadedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoUploadedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoUploadedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.TextField()),
            ],
        ),
    ]
